# SQL Server for Linux with SQL Practice problems
version: '3'

services:

  db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: secret!Password
    volumes:
      - ./scripts:/home/scripts
    ports:
      - 1433:1433
